
<nav class="top-bar" data-topbar data-options="is_hover=false" role="navigation">
  <!-- <img class=" logo maw-100 rs d-n_2" src="https://d2slcw3kip6qmk.cloudfront.net/marketing/logos/lucidsoftware-icon-text-white-24x36.png"> -->
  <ul class="title-area">
    <li class="name">
      <h1><a href="#">Simple LDAP Manager</a></h1>
    </li>
     <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><img class="logo" src="https://d2slcw3kip6qmk.cloudfront.net/app/webroot/img/logos/lucidchart-logo-white-2015.svg"></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <li id ="user-ss-topright" class="has-dropdown">
        <a href="user-chpass-ss.php">Self-Service</a>
        <ul class="dropdown">
          <li><a href="user-chpass-ss.php">Change Password</a></li>
          <li><a href="user-vpn-ss.php">Regenerate VPN Credentials</a></li>
          <li><a href="user-ssh-ss.php">Regenerate SSH Credentials</a></li>
        </ul>
      </li>
      <li class="divider"></li>
      <li id="admin-ss-topright" class="has-dropdown">
        <a href="admin-ss.php">Admin</a>
        <ul class="dropdown">
          <li><a href="admin-ss.php#panel2-1">Reset Password</a></li>
          <li><a href="admin-ss.php#panel2-2">Manage Users</a></li>
          <li><a href="admin-ss.php#panel2-3">Add New User</a></li>
	  <li><a href="admin-ss.php#panel2-4">User Search</a></li>
	  <li><a href="admin-ss.php#panel2-5">Groups Search</a></li>
        </ul>
      </li>
    </ul>

    <!-- Left Nav Section -->

  </section>
</nav>
